#!/usr/bin/env bash
# diging www
getDNS () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ $# -eq 1 ]; then
    getDNS "$1" "www"
    getDNS "$1" "lb-01"
    getDNS "$1" "web-01"
    getDNS "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    getDNS "$1" "$2"
fi
