#!/usr/bin/env bash
# configure a brand you server with nginx web sever and add new header to response
sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee -a /var/www/html/index.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee -a "/var/www/html/404.html" > /dev/null

sed -i "/server_name _;/a\ \trewrite ^/redirect_me/?.*$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sed -i "/rewrite/a\ \terror_page 404 =404 /404.html;" /etc/nginx/sites-available/default
sed -i "/error_page/a\ \tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

service nginx restart
