#!/usr/bin/env bash
# Install and Configure HAproxy
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt-get -y update
sudo apt-get -y install haproxy=2.7.\*

# Configure frontend
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web_servers\n" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

# Configure backend
echo -e "\nbackend web_servers\n\tbalance roundrobin\n\tmode http\n\tserver 195967-web-01 18.234.168.215:80 check\n\tserver 195967-web-02 52.72.71.162:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy restart
