#!/usr/bin/env bash
# ensuring Ngnix installation listen on port 80
sed -i -e "s/\/etc\/nginx\/sites-enabled\/\*/\/etc\/nginx\/sites-available\/\*/" /etc/nginx/nginx.conf
service nginx reload
kill -9 $(cat /var/run/nginx.pid)
