#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely

echo "$$" > /var/run/myscript.pid
while :
do
	echo "To infinity and beyond"
	trap "echo 'I hate the kill command' && rm /var/run/myscript.pid && exit" 15
	trap "echo 'Y U no love me?!' && rm /var/run/myscript.pid && exit" 2
	trap "rm /var/run/myscript.pid && exit" 3
done
