#!/usr/bin/env bash
# This bash script that displays the content of the file /etc/passwd
#	username
#	user id
#	Home directory path of the user

filename=/etc/passwd
while read -r line
do
	echo "$line" | cut -d':' -f1,3,6
done < $filename
