#!/usr/bin/env bash
# This scripts displays the visitors IP along with the HTTP status code from apache log file
# Format: OCCURENCE_NUMBER IP HTTP_CODE
#	in a list format

awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -nr -k1
