#!/usr/bin/env bash
# This script configures an Ubuntu server with the bellow requirements:
#	Requirements:
#		- localhost resolves to 127.0.0.2
#		- facebook resolves to 8.8.8.8
cp -f /etc/hosts ~/hosts.old
sed -i s/^127.0.0.1/127.0.0.2/ /etc/hosts
sed -i -e '$a\8.8.8.8 facebook.com' /etc/hosts
